### ISSUE TITLE
Where to put client_secrets.json

### ISSUE THREAD

**Issue by ManuCart** [leocrawford/picasawebsync#31]
I have this error
````
Traceback (most recent call last):
  File "/usr/local/bin/picasawebsync.py", line 727, in <module>
    gd_client = oauthLogin()
  File "/usr/local/bin/picasawebsync.py", line 660, in oauthLogin
    flow = client.flow_from_clientsecrets('client_secrets.json',scope='https://picasaweb.google.com/data/',redirect_uri='urn:ietf:wg:oauth:2.0:oob')
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 2053, in flow_from_clientsecrets
    client_type, client_info = clientsecrets.loadfile(filename, cache=cache)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/clientsecrets.py", line 155, in loadfile
    return _loadfile(filename)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/clientsecrets.py", line 115, in _loadfile
    raise InvalidClientSecretsError('File not found: "%s"' % filename)
oauth2client.clientsecrets.InvalidClientSecretsError: File not found: "client_secrets.json"
````
I put the file ````client_secrets.json```` on /usr/local/bin and on /home/ but not working

**Comment by ManuCart** [comment]
I found the error, I need to reboot the system to do it working
Strange...
