### ISSUE TITLE
Error when finishing to upload

### ISSUE THREAD

**Issue by ManuCart** [leocrawford/picasawebsync#43]
````
Finished transferring files. Total files found 31364, composed of {'DELETE_REMOTE': 3, 'SILENT': 0, 'UPLOAD_LOCAL': 6871, 'UPDATE_REMOTE_METADATA': 9850, 'DELETE_LOCAL': 0, 'TAG_REMOTE': 0, 'DOWNLOAD_REMOTE': 0, 'REPORT': 0, 'REPLACE_REMOTE_WITH_LOCAL': 14640}
Deleting empty album Auto Backup
Traceback (most recent call last):
  File "/home/pi/.bin/picasawebsync.py", line 772, in <module>
    albums.deleteEmptyWebAlbums(args.owner)
  File "/home/pi/.bin/picasawebsync.py", line 182, in deleteEmptyWebAlbums
    gd_client.Delete(webAlbum)
  File "/usr/lib/python2.7/dist-packages/gdata/photos/service.py", line 659, in Delete
    return gdata.service.GDataService.Delete(self, uri, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/gdata/service.py", line 1429, in Delete
    headers=extra_headers, url_params=url_params)
  File "/usr/lib/python2.7/dist-packages/atom/__init__.py", line 92, in optional_warn_function
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/atom/service.py", line 185, in request
    data=data, headers=all_headers)
  File "/usr/lib/python2.7/dist-packages/atom/http_interface.py", line 148, in perform_request
    return http_client.request(operation, url, data=data, headers=headers)
  File "/usr/lib/python2.7/dist-packages/atom/http.py", line 129, in request
    raise atom.http_interface.UnparsableUrlObject('Unable to parse url '
atom.http_interface.UnparsableUrlObject: Unable to parse url parameter because it was not a string or atom.url.Url
````

**Comment by leocrawford** [comment]
Are you on the very latest version?

**Comment by ManuCart** [comment]
Yes I confirm this is the latest verion
And run again with the same error
````
Finished transferring files. Total files found 31554, composed of {'DELETE_REMOTE': 0, 'SILENT': 31549, 'UPLOAD_LOCAL': 5, 'UPDATE_REMOTE_METADATA': 0, 'DELETE_LOCAL': 0, 'TAG_REMOTE': 0, 'DOWNLOAD_REMOTE': 0, 'REPORT': 0, 'REPLACE_REMOTE_WITH_LOCAL': 0}
Deleting empty album Auto Backup
Traceback (most recent call last):
  File "/home/pi/.bin/picasawebsync.py", line 772, in <module>
    albums.deleteEmptyWebAlbums(args.owner)
  File "/home/pi/.bin/picasawebsync.py", line 182, in deleteEmptyWebAlbums
    gd_client.Delete(webAlbum)
  File "/usr/lib/python2.7/dist-packages/gdata/photos/service.py", line 659, in Delete
    return gdata.service.GDataService.Delete(self, uri, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/gdata/service.py", line 1429, in Delete
    headers=extra_headers, url_params=url_params)
  File "/usr/lib/python2.7/dist-packages/atom/__init__.py", line 92, in optional_warn_function
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/atom/service.py", line 185, in request
    data=data, headers=all_headers)
  File "/usr/lib/python2.7/dist-packages/atom/http_interface.py", line 148, in perform_request
    return http_client.request(operation, url, data=data, headers=headers)
  File "/usr/lib/python2.7/dist-packages/atom/http.py", line 129, in request
    raise atom.http_interface.UnparsableUrlObject('Unable to parse url '
atom.http_interface.UnparsableUrlObject: Unable to parse url parameter because it was not a string or atom.url.Url
````

**Comment by leocrawford** [comment]
Do you want to try the recent commit and see if that helps?

**Comment by ManuCart** [comment]
Thanks it's working!
